name: CI/CD Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3️⃣ Set up Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: pysql-gym12
          export_default_credentials: true

      # 4️⃣ Configure Docker for Artifact Registry
      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # 5️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/pysql-gym12/fastapi-repo/fastapi-app:latest .

      # 6️⃣ Push Docker image
      - name: Push Docker image
        run: |
          docker push us-central1-docker.pkg.dev/pysql-gym12/fastapi-repo/fastapi-app:latest

      # 7️⃣ Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-service \
            --image us-central1-docker.pkg.dev/pysql-gym12/fastapi-repo/fastapi-app:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --update-env-vars SQLALCHEMY_DATABASE_URL=${{ secrets.SQLALCHEMY_DATABASE_URL }}
